--
-- PostgreSQL database dump
--

\restrict 8iCrJ1vmnOnC73a4BIcvoBxZ9hhpuief1HNiIL56tedjB7CEXb5ku9XPR1MUtrJ

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AIAssessments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AIAssessments" (
    "AIAssessmentId" integer NOT NULL,
    "ConsultationId" integer NOT NULL,
    "AssessmentReport" character varying(2000) NOT NULL,
    "PossibleConditions" character varying(500),
    "SuggestedQuestions" character varying(1000),
    "ConfidenceScore" numeric(5,2),
    "RedFlags" character varying(1000),
    "GeneratedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."AIAssessments" OWNER TO postgres;

--
-- Name: AIAssessments_AIAssessmentId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AIAssessments" ALTER COLUMN "AIAssessmentId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AIAssessments_AIAssessmentId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Allergies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Allergies" (
    "AllergyId" integer NOT NULL,
    "PatientId" integer NOT NULL,
    "AllergenName" character varying(200) NOT NULL,
    "Reaction" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "AllergyType" integer DEFAULT 1 CONSTRAINT "Allergies_AllergyType_Temp_not_null" NOT NULL,
    "Severity" integer DEFAULT 1 CONSTRAINT "Allergies_Severity_Temp_not_null" NOT NULL
);


ALTER TABLE public."Allergies" OWNER TO postgres;

--
-- Name: Allergies_AllergyId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Allergies" ALTER COLUMN "AllergyId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Allergies_AllergyId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO postgres;

--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO postgres;

--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO postgres;

--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO postgres;

--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO postgres;

--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "UserType" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO postgres;

--
-- Name: Consultations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Consultations" (
    "ConsultationId" integer NOT NULL,
    "PatientId" integer NOT NULL,
    "Symptoms" character varying(2000) NOT NULL,
    "SymptomDuration" character varying(50),
    "SymptomSeverity" character varying(50),
    "AdditionalInformation" character varying(1000),
    "Status" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    "PharmacistId" text,
    "ReviewedAt" timestamp without time zone
);


ALTER TABLE public."Consultations" OWNER TO postgres;

--
-- Name: Consultations_ConsultationId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Consultations" ALTER COLUMN "ConsultationId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Consultations_ConsultationId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: CurrentMedications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CurrentMedications" (
    "CurrentMedicationId" integer NOT NULL,
    "PatientId" integer NOT NULL,
    "MedicationName" character varying(200) NOT NULL,
    "Dosage" character varying(100),
    "Frequency" character varying(100),
    "StartDate" timestamp with time zone,
    "Purpose" character varying(500),
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."CurrentMedications" OWNER TO postgres;

--
-- Name: CurrentMedications_CurrentMedicationId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CurrentMedications" ALTER COLUMN "CurrentMedicationId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CurrentMedications_CurrentMedicationId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Inventories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Inventories" (
    "InventoryId" integer NOT NULL,
    "MedicineName" character varying(200) NOT NULL,
    "Description" character varying(500),
    "QuantityInStock" integer NOT NULL,
    "Unit" character varying(50) NOT NULL,
    "Price" numeric NOT NULL,
    "ReorderLevel" integer NOT NULL,
    "ExpiryDate" timestamp without time zone,
    "Manufacturer" character varying(100),
    "Category" character varying(100),
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."Inventories" OWNER TO postgres;

--
-- Name: Inventories_InventoryId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Inventories" ALTER COLUMN "InventoryId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Inventories_InventoryId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MedicalHistories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MedicalHistories" (
    "MedicalHistoryId" integer NOT NULL,
    "PatientId" integer NOT NULL,
    "ConditionName" character varying(200) NOT NULL,
    "DiagnosedDate" timestamp with time zone,
    "Notes" character varying(500),
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."MedicalHistories" OWNER TO postgres;

--
-- Name: MedicalHistories_MedicalHistoryId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."MedicalHistories" ALTER COLUMN "MedicalHistoryId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MedicalHistories_MedicalHistoryId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Medications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Medications" (
    "MedicationId" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "GenericName" character varying(200),
    "Category" character varying(100),
    "Description" character varying(1000),
    "Price" numeric(10,2),
    "StockQuantity" integer NOT NULL,
    "RequiresPrescription" boolean NOT NULL,
    "IsAvailable" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone
);


ALTER TABLE public."Medications" OWNER TO postgres;

--
-- Name: Medications_MedicationId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Medications" ALTER COLUMN "MedicationId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Medications_MedicationId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Patients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Patients" (
    "PatientId" integer NOT NULL,
    "UserId" text NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    "Gender" character varying(10) NOT NULL,
    "Address" character varying(200),
    "City" character varying(100),
    "EmergencyContact" character varying(20),
    "Height" numeric(5,2),
    "Weight" numeric(5,2),
    "IsPregnant" boolean NOT NULL,
    "IsBreastfeeding" boolean NOT NULL,
    "AdditionalNotes" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "HasKidneyDisease" boolean DEFAULT false NOT NULL,
    "HasLiverDisease" boolean DEFAULT false NOT NULL,
    "HasDrugAllergies" boolean DEFAULT false NOT NULL,
    "DrugAllergyDetails" character varying(500),
    "SmokingStatus" integer,
    "ExerciseFrequency" integer,
    "AlcoholConsumption" integer,
    "BloodType" integer
);


ALTER TABLE public."Patients" OWNER TO postgres;

--
-- Name: Patients_PatientId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Patients" ALTER COLUMN "PatientId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Patients_PatientId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Recommendations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Recommendations" (
    "RecommendationId" integer NOT NULL,
    "ConsultationId" integer NOT NULL,
    "PharmacistId" text NOT NULL,
    "InventoryId" integer,
    "PharmacistNotes" character varying(2000) NOT NULL,
    "Dosage" character varying(500),
    "Instructions" character varying(1000),
    "Warnings" character varying(1000),
    "ReferToDoctor" boolean NOT NULL,
    "ReferralReason" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Recommendations" OWNER TO postgres;

--
-- Name: Recommendations_RecommendationId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Recommendations" ALTER COLUMN "RecommendationId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Recommendations_RecommendationId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: patients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.patients (
    patient_id integer NOT NULL,
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    date_of_birth timestamp with time zone NOT NULL,
    gender character varying(10) NOT NULL,
    phone character varying(20) NOT NULL,
    address character varying(200) NOT NULL,
    blood_type character varying(5) NOT NULL,
    height integer,
    weight numeric(5,2),
    emergency_contact character varying(20) NOT NULL,
    chronic_diseases character varying(500) NOT NULL,
    allergies character varying(500) NOT NULL,
    current_medications character varying(500) NOT NULL,
    past_surgeries character varying(500) NOT NULL,
    family_history character varying(500) NOT NULL,
    smoking_status character varying(20) NOT NULL,
    alcohol_consumption character varying(20) NOT NULL,
    exercise_frequency character varying(30) NOT NULL,
    age integer,
    bmi numeric,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone
);


ALTER TABLE public.patients OWNER TO postgres;

--
-- Name: patients_patient_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.patients ALTER COLUMN patient_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patients_patient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pharmacists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pharmacists (
    pharmacist_id integer NOT NULL,
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    phone character varying(20) NOT NULL,
    license_number character varying(50) NOT NULL,
    pharmacy_name character varying(100) NOT NULL,
    pharmacy_address character varying(200) NOT NULL,
    specialization character varying(100) NOT NULL,
    years_of_experience integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone
);


ALTER TABLE public.pharmacists OWNER TO postgres;

--
-- Name: pharmacists_pharmacist_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pharmacists ALTER COLUMN pharmacist_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pharmacists_pharmacist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    email character varying(100) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(20) DEFAULT 'Patient'::character varying NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AIAssessments PK_AIAssessments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AIAssessments"
    ADD CONSTRAINT "PK_AIAssessments" PRIMARY KEY ("AIAssessmentId");


--
-- Name: Allergies PK_Allergies; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Allergies"
    ADD CONSTRAINT "PK_Allergies" PRIMARY KEY ("AllergyId");


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: Consultations PK_Consultations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Consultations"
    ADD CONSTRAINT "PK_Consultations" PRIMARY KEY ("ConsultationId");


--
-- Name: CurrentMedications PK_CurrentMedications; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CurrentMedications"
    ADD CONSTRAINT "PK_CurrentMedications" PRIMARY KEY ("CurrentMedicationId");


--
-- Name: Inventories PK_Inventories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Inventories"
    ADD CONSTRAINT "PK_Inventories" PRIMARY KEY ("InventoryId");


--
-- Name: MedicalHistories PK_MedicalHistories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MedicalHistories"
    ADD CONSTRAINT "PK_MedicalHistories" PRIMARY KEY ("MedicalHistoryId");


--
-- Name: Medications PK_Medications; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Medications"
    ADD CONSTRAINT "PK_Medications" PRIMARY KEY ("MedicationId");


--
-- Name: Patients PK_Patients; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Patients"
    ADD CONSTRAINT "PK_Patients" PRIMARY KEY ("PatientId");


--
-- Name: Recommendations PK_Recommendations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Recommendations"
    ADD CONSTRAINT "PK_Recommendations" PRIMARY KEY ("RecommendationId");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: patients PK_patients; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT "PK_patients" PRIMARY KEY (patient_id);


--
-- Name: pharmacists PK_pharmacists; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pharmacists
    ADD CONSTRAINT "PK_pharmacists" PRIMARY KEY (pharmacist_id);


--
-- Name: users PK_users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT "PK_users" PRIMARY KEY (user_id);


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_AIAssessments_ConsultationId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_AIAssessments_ConsultationId" ON public."AIAssessments" USING btree ("ConsultationId");


--
-- Name: IX_Allergies_PatientId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Allergies_PatientId" ON public."Allergies" USING btree ("PatientId");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: IX_Consultations_CreatedAt; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Consultations_CreatedAt" ON public."Consultations" USING btree ("CreatedAt");


--
-- Name: IX_Consultations_PatientId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Consultations_PatientId" ON public."Consultations" USING btree ("PatientId");


--
-- Name: IX_Consultations_PharmacistId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Consultations_PharmacistId" ON public."Consultations" USING btree ("PharmacistId");


--
-- Name: IX_Consultations_Status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Consultations_Status" ON public."Consultations" USING btree ("Status");


--
-- Name: IX_CurrentMedications_PatientId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_CurrentMedications_PatientId" ON public."CurrentMedications" USING btree ("PatientId");


--
-- Name: IX_MedicalHistories_PatientId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MedicalHistories_PatientId" ON public."MedicalHistories" USING btree ("PatientId");


--
-- Name: IX_Medications_IsAvailable; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Medications_IsAvailable" ON public."Medications" USING btree ("IsAvailable");


--
-- Name: IX_Medications_Name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Medications_Name" ON public."Medications" USING btree ("Name");


--
-- Name: IX_Patients_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Patients_UserId" ON public."Patients" USING btree ("UserId");


--
-- Name: IX_Recommendations_ConsultationId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Recommendations_ConsultationId" ON public."Recommendations" USING btree ("ConsultationId");


--
-- Name: IX_Recommendations_InventoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Recommendations_InventoryId" ON public."Recommendations" USING btree ("InventoryId");


--
-- Name: IX_Recommendations_PharmacistId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Recommendations_PharmacistId" ON public."Recommendations" USING btree ("PharmacistId");


--
-- Name: IX_patients_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_patients_user_id" ON public.patients USING btree (user_id);


--
-- Name: IX_pharmacists_license_number; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_pharmacists_license_number" ON public.pharmacists USING btree (license_number);


--
-- Name: IX_pharmacists_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_pharmacists_user_id" ON public.pharmacists USING btree (user_id);


--
-- Name: IX_users_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_users_email" ON public.users USING btree (email);


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: AIAssessments FK_AIAssessments_Consultations_ConsultationId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AIAssessments"
    ADD CONSTRAINT "FK_AIAssessments_Consultations_ConsultationId" FOREIGN KEY ("ConsultationId") REFERENCES public."Consultations"("ConsultationId") ON DELETE CASCADE;


--
-- Name: Allergies FK_Allergies_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Allergies"
    ADD CONSTRAINT "FK_Allergies_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("PatientId") ON DELETE CASCADE;


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Consultations FK_Consultations_AspNetUsers_PharmacistId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Consultations"
    ADD CONSTRAINT "FK_Consultations_AspNetUsers_PharmacistId" FOREIGN KEY ("PharmacistId") REFERENCES public."AspNetUsers"("Id");


--
-- Name: Consultations FK_Consultations_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Consultations"
    ADD CONSTRAINT "FK_Consultations_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("PatientId") ON DELETE CASCADE;


--
-- Name: CurrentMedications FK_CurrentMedications_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CurrentMedications"
    ADD CONSTRAINT "FK_CurrentMedications_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("PatientId") ON DELETE CASCADE;


--
-- Name: MedicalHistories FK_MedicalHistories_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MedicalHistories"
    ADD CONSTRAINT "FK_MedicalHistories_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("PatientId") ON DELETE CASCADE;


--
-- Name: Patients FK_Patients_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Patients"
    ADD CONSTRAINT "FK_Patients_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Recommendations FK_Recommendations_AspNetUsers_PharmacistId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Recommendations"
    ADD CONSTRAINT "FK_Recommendations_AspNetUsers_PharmacistId" FOREIGN KEY ("PharmacistId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Recommendations FK_Recommendations_Consultations_ConsultationId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Recommendations"
    ADD CONSTRAINT "FK_Recommendations_Consultations_ConsultationId" FOREIGN KEY ("ConsultationId") REFERENCES public."Consultations"("ConsultationId") ON DELETE CASCADE;


--
-- Name: Recommendations FK_Recommendations_Inventories_InventoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Recommendations"
    ADD CONSTRAINT "FK_Recommendations_Inventories_InventoryId" FOREIGN KEY ("InventoryId") REFERENCES public."Inventories"("InventoryId");


--
-- Name: patients FK_patients_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT "FK_patients_users_user_id" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: pharmacists FK_pharmacists_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pharmacists
    ADD CONSTRAINT "FK_pharmacists_users_user_id" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 8iCrJ1vmnOnC73a4BIcvoBxZ9hhpuief1HNiIL56tedjB7CEXb5ku9XPR1MUtrJ

