<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\PharmaCare.Data\PharmaCare.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MailKit" Version="4.15.0" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.5" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore.Hosting.Abstractions">
        <HintPath>..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.8\Microsoft.AspNetCore.Hosting.Abstractions.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.AspNetCore.Http.Features">
        <HintPath>..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.8\Microsoft.AspNetCore.Http.Features.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
